services:
  ec2-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: msp-ec2-monitor:latest
    container_name: ec2-cross-account-monitor
    environment:
      
      # Application configuration
      SOURCE_ACCOUNT_ID: ${SOURCE_ACCOUNT_ID}
      TARGET_ACCOUNT_ID: ${TARGET_ACCOUNT_ID}
      ASSUME_ROLE_NAME: ${ASSUME_ROLE_NAME}
      SESSION_NAME: ${SESSION_NAME:-EC2ListingSession}
      AWS_REGION: ${AWS_REGION:-ap-northeast-2}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      # Mount AWS credentials from host (for local testing only)
      # - ~/.aws:/home/appuser/.aws:ro
      
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    # For running on EC2 with IAM role
    network_mode: host